### ISSUE TITLE
GetParameters execution failed on Linux

### ISSUE THREAD

**Issue by uttne** [uttne/ArgsToClass#20]
Calling GetParameters by executing ArgsToClass.ArgsDataExtensions.GetExtensionMethodInfos on Linux causes an exception.

```
Microsoft (R) Test Execution Command Line Tool Version 16.3.0
Copyright (c) Microsoft Corporation.  All rights reserved.

テスト実行を開始しています。お待ちください...

合計 1 個のテスト ファイルが指定されたパターンと一致しました。
  X ArgsToClass.Tests.ArgsDataExtensionsTest.RunCommandTest [147ms]
  エラー メッセージ:
   System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime'. The system cannot find the file specified.

  スタック トレース:
     at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeMethodInfo.FetchNonReturnParameters()
   at System.Reflection.RuntimeMethodInfo.GetParameters()
   at ArgsToClass.ArgsDataExtensions.<>c__DisplayClass0_0.<GetExtensionMethodInfos>b__4(MethodInfo x) in /home/main/ArgsToClass/src/ArgsToClass/ArgsDataExtensions.cs:line 16
   at System.Linq.Utilities.<>c__DisplayClass1_0`1.<CombinePredicates>b__0(TSource x)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at ArgsToClass.ArgsDataExtensions.GetExtensionMethodInfos(Type type) in /home/main/ArgsToClass/src/ArgsToClass/ArgsDataExtensions.cs:line 11
   at ArgsToClass.ArgsDataExtensions.RunCommand(Object command) in /home/main/ArgsToClass/src/ArgsToClass/ArgsDataExtensions.cs:line 53
   at ArgsToClass.Tests.ArgsDataExtensionsTest.RunCommandTest() in /home/main/ArgsToClass/src/ArgsToClass.Tests/ArgsDataExtensionsTest.cs:line 113
  X ArgsToClass.Tests.ArgsDataExtensionsTest.GetExtensionMethodInfosTest [45ms]
  エラー メッセージ:
   System.IO.FileNotFoundException : Could not load file or assembly 'Windows, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime'. The system cannot find the file specified.

  スタック トレース:
     at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RuntimeMethodInfo.FetchNonReturnParameters()
   at System.Reflection.RuntimeMethodInfo.GetParameters()
   at ArgsToClass.ArgsDataExtensions.<>c__DisplayClass0_0.<GetExtensionMethodInfos>b__4(MethodInfo x) in /home/main/ArgsToClass/src/ArgsToClass/ArgsDataExtensions.cs:line 16
   at System.Linq.Utilities.<>c__DisplayClass1_0`1.<CombinePredicates>b__0(TSource x)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at ArgsToClass.ArgsDataExtensions.GetExtensionMethodInfos(Type type) in /home/main/ArgsToClass/src/ArgsToClass/ArgsDataExtensions.cs:line 11
   at ArgsToClass.Tests.ArgsDataExtensionsTest.GetExtensionMethodInfosTest() in /home/main/ArgsToClass/src/ArgsToClass.Tests/ArgsDataExtensionsTest.cs:line 97
```

**Comment by uttne** [comment]
# Investigation.
For System.Threading.Tasks.Task AsTask (Windows.Foundation.IAsyncAction) defined in 
{Name = "WindowsRuntimeSystemExtensions" FullName = "System.WindowsRuntimeSystemExtensions"}.

The IAsyncAction parameter 1 is defined in the following assembly, but it seems that this assembly does not exist in the Linux environment.
{Windows.Foundation, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime}
